/**
 * Sample data presets for email template previews and testing
 */

export interface SampleDataPreset {
  key: string;
  label: string;
  description: string;
  data: Record<string, string | number | boolean>;
}

export const SAMPLE_DATA_PRESETS: SampleDataPreset[] = [
  {
    key: 'new_user',
    label: 'New User',
    description: 'Just signed up, no activity yet',
    data: {
      userName: 'Jane Smith',
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane@example.com',
      goalProgress: '0%',
      caloriesConsumed: '0',
      caloriesGoal: '2000',
      proteinConsumed: '0g',
      proteinGoal: '150g',
      carbsConsumed: '0g',
      carbsGoal: '250g',
      fatConsumed: '0g',
      fatGoal: '70g',
      currentWeight: '180 lbs',
      goalWeight: '165 lbs',
      weightProgress: '0 lbs',
      restingHeartRate: '--',
      hrv: '--',
      sleepDuration: '--',
      subscriptionTier: 'Free',
      subscriptionExpiresAt: '--',
      trialDaysRemaining: '0',
      appName: 'Nutri',
      actionUrl: 'https://nutri.app/action',
      unsubscribeUrl: 'https://nutri.app/unsubscribe',
      preferencesUrl: 'https://nutri.app/preferences',
      supportEmail: 'support@nutri.app',
    },
  },
  {
    key: 'active_user',
    label: 'Active User (7-day streak)',
    description: 'Consistently tracking meals for a week',
    data: {
      userName: 'Mike Johnson',
      firstName: 'Mike',
      lastName: 'Johnson',
      email: 'mike@example.com',
      goalProgress: '75%',
      caloriesConsumed: '1850',
      caloriesGoal: '2000',
      proteinConsumed: '120g',
      proteinGoal: '150g',
      carbsConsumed: '200g',
      carbsGoal: '250g',
      fatConsumed: '55g',
      fatGoal: '70g',
      currentWeight: '175 lbs',
      goalWeight: '165 lbs',
      weightProgress: '-5 lbs',
      restingHeartRate: '65 bpm',
      hrv: '45 ms',
      sleepDuration: '7h 30m',
      subscriptionTier: 'Free',
      subscriptionExpiresAt: '--',
      trialDaysRemaining: '0',
      appName: 'Nutri',
      actionUrl: 'https://nutri.app/action',
      unsubscribeUrl: 'https://nutri.app/unsubscribe',
      preferencesUrl: 'https://nutri.app/preferences',
      supportEmail: 'support@nutri.app',
    },
  },
  {
    key: 'premium_user',
    label: 'Premium User',
    description: 'Pro subscriber with all features unlocked',
    data: {
      userName: 'Sarah Williams',
      firstName: 'Sarah',
      lastName: 'Williams',
      email: 'sarah@example.com',
      goalProgress: '92%',
      caloriesConsumed: '1750',
      caloriesGoal: '1800',
      proteinConsumed: '135g',
      proteinGoal: '140g',
      carbsConsumed: '180g',
      carbsGoal: '200g',
      fatConsumed: '60g',
      fatGoal: '65g',
      currentWeight: '145 lbs',
      goalWeight: '140 lbs',
      weightProgress: '-15 lbs',
      restingHeartRate: '58 bpm',
      hrv: '55 ms',
      sleepDuration: '8h 15m',
      subscriptionTier: 'Pro',
      subscriptionExpiresAt: 'Jan 15, 2026',
      trialDaysRemaining: '0',
      appName: 'Nutri',
      actionUrl: 'https://nutri.app/action',
      unsubscribeUrl: 'https://nutri.app/unsubscribe',
      preferencesUrl: 'https://nutri.app/preferences',
      supportEmail: 'support@nutri.app',
    },
  },
  {
    key: 'inactive_user',
    label: 'Inactive User',
    description: '14 days since last activity',
    data: {
      userName: 'Tom Brown',
      firstName: 'Tom',
      lastName: 'Brown',
      email: 'tom@example.com',
      goalProgress: '45%',
      caloriesConsumed: '0',
      caloriesGoal: '2200',
      proteinConsumed: '0g',
      proteinGoal: '160g',
      carbsConsumed: '0g',
      carbsGoal: '275g',
      fatConsumed: '0g',
      fatGoal: '75g',
      currentWeight: '195 lbs',
      goalWeight: '175 lbs',
      weightProgress: '-5 lbs',
      restingHeartRate: '72 bpm',
      hrv: '35 ms',
      sleepDuration: '6h',
      subscriptionTier: 'Free',
      subscriptionExpiresAt: '--',
      trialDaysRemaining: '0',
      appName: 'Nutri',
      actionUrl: 'https://nutri.app/come-back',
      unsubscribeUrl: 'https://nutri.app/unsubscribe',
      preferencesUrl: 'https://nutri.app/preferences',
      supportEmail: 'support@nutri.app',
    },
  },
  {
    key: 'goal_achieved',
    label: 'Goal Achieved',
    description: 'User who reached their target weight',
    data: {
      userName: 'Lisa Chen',
      firstName: 'Lisa',
      lastName: 'Chen',
      email: 'lisa@example.com',
      goalProgress: '100%',
      caloriesConsumed: '1650',
      caloriesGoal: '1700',
      proteinConsumed: '125g',
      proteinGoal: '130g',
      carbsConsumed: '170g',
      carbsGoal: '180g',
      fatConsumed: '55g',
      fatGoal: '60g',
      currentWeight: '135 lbs',
      goalWeight: '135 lbs',
      weightProgress: '-25 lbs',
      restingHeartRate: '55 bpm',
      hrv: '60 ms',
      sleepDuration: '7h 45m',
      subscriptionTier: 'Pro',
      subscriptionExpiresAt: 'Mar 20, 2026',
      trialDaysRemaining: '0',
      appName: 'Nutri',
      actionUrl: 'https://nutri.app/celebrate',
      unsubscribeUrl: 'https://nutri.app/unsubscribe',
      preferencesUrl: 'https://nutri.app/preferences',
      supportEmail: 'support@nutri.app',
    },
  },
  {
    key: 'trial_user',
    label: 'Trial User',
    description: 'Pro trial with 5 days remaining',
    data: {
      userName: 'Alex Rivera',
      firstName: 'Alex',
      lastName: 'Rivera',
      email: 'alex@example.com',
      goalProgress: '60%',
      caloriesConsumed: '1900',
      caloriesGoal: '2100',
      proteinConsumed: '140g',
      proteinGoal: '155g',
      carbsConsumed: '220g',
      carbsGoal: '260g',
      fatConsumed: '65g',
      fatGoal: '72g',
      currentWeight: '168 lbs',
      goalWeight: '155 lbs',
      weightProgress: '-7 lbs',
      restingHeartRate: '68 bpm',
      hrv: '40 ms',
      sleepDuration: '7h',
      subscriptionTier: 'Trial',
      subscriptionExpiresAt: 'Jan 5, 2025',
      trialDaysRemaining: '5',
      appName: 'Nutri',
      actionUrl: 'https://nutri.app/upgrade',
      unsubscribeUrl: 'https://nutri.app/unsubscribe',
      preferencesUrl: 'https://nutri.app/preferences',
      supportEmail: 'support@nutri.app',
    },
  },
];

export function getSampleDataByKey(key: string): Record<string, string | number | boolean> {
  const preset = SAMPLE_DATA_PRESETS.find((p) => p.key === key);
  return preset?.data || SAMPLE_DATA_PRESETS[0].data;
}

export default SAMPLE_DATA_PRESETS;
